apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyaml
    enviroment: naomi
  name: podyaml
spec:
  containers:
  - image: nginx
    name: podyaml 
    volumeMounts:
      - mountPath: "/scratch"
        name: my-volume  
    resources: {}
  volumes:
    - name: my-volume
      emptyDir:
        sizeLimit: 50Mi
  dnsPolicy: ClusterFirst    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
