apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: podyaml
    enviroment: naomi
  name: podyaml
spec:
  containers:
  - image: nginx
    name: podyaml 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
