apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: naodeplo
  name: naodeplo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: naodeplo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: naodeplo
    spec:
      containers:
      - image: nginx:mainline-perl
        name: nginx
        resources: {}
status: {}